### ISSUE TITLE
Mass production

### ISSUE THREAD

**Issue by xfce** [twlostow/dsi-shield#16]
Hi
    @twlostow  and all,
I think I can help to mass product, as I am interested in FPGA, also use spatarn6 and adv7611( the hdmilight project on github),
my project is here https://hackaday.io/project/189703-pinuo-fpga-hdmi-ambilight-control-system

[https://hackaday.io/project/189703-pinuo-fpga-hdmi-ambilight-control-system](url)

**Comment by twlostow** [comment]
Hi,

Cool project (HDMILight)!. In the case of the MIPI adapter, the problem is not in the mass production, but in the mass support. Over the course of many years (since 2014 when this got published first), I've got hundreds of emails asking to sell the device, adapted to a particular display (meaning a PCB variant and quite often reverse engineering the init sequence). Potential buyers are eager to pay $100 or less... I don't think this is really worth the effort.

T.

**Comment by xfce** [comment]
OK, 
       If you have any plan, feel free to tell me, maybe I can help ^_^
